# Chemist can be built using the
# same base image as that of
# TensorWrapper. This workflow
# just tag the base image of TensorWrapper

name: Tag the base image of TensorWrapper

on:
  workflow_call:

jobs:
  tag-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REPO_TOKEN }}
      - name: Tag the base image of TensorWrapper
        run: |
          docker pull ghcr.io/nwchemex-project/base_tensorwrapper:latest
          docker tag ghcr.io/nwchemex-project/base_tensorwrapper:latest ghcr.io/nwchemex-project/base_chemist:latest
          docker push ghcr.io/nwchemex-project/base_chemist:latest
          docker pull ghcr.io/nwchemex-project/base_tensorwrapper:stable
          docker tag ghcr.io/nwchemex-project/base_tensorwrapper:stable ghcr.io/nwchemex-project/base_chemist:stable
          docker push ghcr.io/nwchemex-project/base_chemist:stable
