name: C_C++_CI
on:
  pull_request:
    branches:
      - master

jobs:
  build-with-gcc:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@cache-build2
    with: 
      dependencies: 'ninja gcc gcovr openblas cblas lapacke scalapack boost eigen3 openmpi'
      clang-build: false
      gcc-build: true
      ninja_build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
  
  build-with-clang:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@cache-build2
    with: 
      dependencies: 'ninja clang gcovr openblas cblas lapacke scalapack boost eigen3 openmpi'
      clang-build: true
      gcc-build: false
      ninja_build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
