name: C_C++_CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - clang-build

jobs:
  build-with-gcc:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@parallel-template
    with: 
      dependencies: 'gcc gcovr openblas cblas lapacke scalapack boost eigen3 openmpi'
      clang-build: false
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
  
  build-with-clang:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@parallel-template
    with: 
      dependencies: 'clang gcovr openblas cblas lapacke scalapack boost eigen3 openmpi'
      clang-build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
