name: C_C++_CI
on:
  pull_request:
    branches:
      - master
  # push:
  #   branches:
  #     - reuseable-workflow

jobs:
  build:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yml@master
    with: 
      dependencies: 'gcc gcovr openblas cblas lapacke scalapack boost eigen3 openmpi'
