name: Test Documentation
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - reuseable-workflow

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/test_docs_tmpl.yml@master
    with:
      target: chemist_cxx_api
      dependencies: cmake doxygen sphinx
